/**
 * GalleryManifest — typed reader for public/assets/gallery_manifest.json, the
 * build-time index of every placeable GLB (generated by
 * scripts/gen_gallery_manifest.mjs — the renderer cannot list directories).
 * Pure parsing/grouping; the fetch lives in the editor scene.
 */

export interface GalleryEntry {
  /** GLB path relative to /assets/, e.g. 'world/guns/pistol.glb'. */
  path: string;
  /** First directory under world/ (or 'items'). */
  category: string;
  /** Human label derived from the file name. */
  label: string;
}

/** Validate the manifest JSON; malformed entries are dropped, not fatal. */
export function parseGalleryManifest(raw: unknown): GalleryEntry[] {
  if (typeof raw !== 'object' || raw === null) return [];
  const entries = (raw as { entries?: unknown }).entries;
  if (!Array.isArray(entries)) return [];
  return entries.filter((e): e is GalleryEntry => {
    if (typeof e !== 'object' || e === null) return false;
    const o = e as Record<string, unknown>;
    return typeof o.path === 'string' && o.path.endsWith('.glb')
      && typeof o.category === 'string' && o.category.length > 0
      && typeof o.label === 'string' && o.label.length > 0;
  });
}

/** Group entries by category, categories sorted alphabetically. */
export function entriesByCategory(entries: GalleryEntry[]): Map<string, GalleryEntry[]> {
  const map = new Map<string, GalleryEntry[]>();
  const cats = [...new Set(entries.map((e) => e.category))].sort();
  for (const c of cats) map.set(c, entries.filter((e) => e.category === c));
  return map;
}

/** 'world/guns/pistol_sci.glb' → 'Pistol Sci'. Mirrors the generator script. */
export function labelFromPath(path: string): string {
  const stem = (path.split('/').pop() ?? path).replace(/\.glb$/i, '');
  return stem.split(/[_-]+/).filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}
